all:
  qty_seats_reserverd: 1
  notificacion_mtc:     'Hoy se vence el MTC del tripulante'
  notificacion_natclar: 'Hoy se vence el NATCLAR del tripulante '
  notificacion_soat:    'Hoy se vence el SOAT del Bus con placa '
  notificacion_poliza:  'Hoy se vence la POLIZA del Bus con placa '
  notificacion_revision_tenica: 'Hoy se vence la REVISION TECNICA del Bus con placa '
  notificacion_tarjeta_circulacion: 'Hoy se vence la TARJETA DE CIRCULACION del Bus con placa '
  cantidad_horas_limite: 2
  email_notificacion_1: davidtataje@gmail.com 
  #rvalencia@glencore.com.pe
  email_notificacion_2: ronald_reyn@hotmail.com
  #jcarpio@glencore.com.pe
  email_notificacion_3: new.skin007@gmail.com
  #ipolo@glencore.com.pe
  email_notificacion_4: reservasmina@polosac.pe
  email_notificacion_5: hperez@polosac.pe
  email_notificacion_6: reservaslima@polosac.pe