all:
  qty_seats_reserverd: 1
  notificacion_mtc:     'Hoy se vence el MTC del tripulante'
  notificacion_natclar: 'Hoy se vence el NATCLAR del tripulante '
  notificacion_soat:    'Hoy se vence el SOAT del Bus con placa '
  notificacion_poliza:  'Hoy se vence la POLIZA del Bus con placa '
  notificacion_revision_tenica: 'Hoy se vence la REVISION TECNICA del Bus con placa '
  notificacion_tarjeta_circulacion: 'Hoy se vence la TARJETA DE CIRCULACION del Bus con placa '
  cantidad_horas_limite: 2
  
  
  email_notification_from: new.skin007@gmail.com #replace for other
  email_notifications:
    davidtataje@gmail.com: Rodrigo Valencia
  #rvalencia@glencore.com.pe
    #ronald_reyn@hotmail.com: Julio Carpio
  #jcarpio@glencore.com.pe
    new.skin007@gmail.com: N&eacute;lia L&oacute;pez
  #ipolo@glencore.com.pe
    #reservasmina@polosac.pe: N&eacute;lia L&oacute;pez
    #hperez@polosac.pe:  Hugo Perez
    #reservaslima@polosac.pe: Iris Canchan
  email_subject: Notificaci&oacute;n Autogenerada por el sistema de reservas POLOSAC