prod:
  logger:
    class:                   sfNoLogger
    param:
      level:                 err
      loggers:               ~
  mailer:
    class: sfMailer
    param:
      logging: %SF_LOGGING_ENABLED%
      charset: %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_MailTransport      

test:
  response:
    class:                   sfWebResponse
    param:
      send_http_headers:     false
      
  storage:
    class:                   sfSessionTestStorage
    param:
      session_path:          %SF_TEST_CACHE_DIR%/sessions
  
  mailer:
    param:
      delivery_strategy:     none

dev:
  mailer:
    param:
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.gmail.com
          port:       465
          encryption: ssl
          username: davidtataje@gmail.com
          password: jasminalexandra1
all:
  routing:
    class:                   sfPatternRoutingExt
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  storage:
    class:                   sfSessionStorage
    param:
      session_name:          polosac
      
  user:
    class: UserBackend
    param:
      timeout: 180000
      logging: %SF_LOGGING_ENABLED%
      use_flash: true
      default_culture: es
  mailer:
    param:
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.gmail.com
          port:       465
          encryption: ssl
          username: davidtataje@gmail.com
          password: jasminalexandra1