########################
####### Passenger ######
########################

#Place
passenger_show:
  url:             /mostrar/pasajero/:slug
  param:           { module: Passenger, action: show }
  requirements:    { slug: \w+ }

passenger_list:
  url:             /lista/pasajeros/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Passenger, action: list, filter_by: id, filter: 0, order_by: names, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

passenger_new:
  url:             /nuevo/pasajero
  param:           { module: Passenger, action: edit }

passenger_edit:
  url:             /editar/pasajero/:slug
  param:           { module: Passenger, action: edit }
  requirements:    { slug: '[\w-]+' }

passenger_delete:
  url:             /eliminar/pasajero/:slug
  param:           { module: Passenger, action: delete }
  requirements:    { slug: '[\w-,]+' }
  

########################
####### Schedule #######
########################

#appointment
schedule_programacion:
  url:             /programaciones/polosac
  param:           { module: Schedule, action: programacion, secure: false }


#Schedule
schedule_show:
  url:             /mostrar/programacion/:slug
  param:           { module: Schedule, action: show }
  requirements:    { slug: \w+ }

schedule_list:
  url:             /lista/programaciones/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Schedule, action: list, filter_by: id, filter: 0, order_by: travel_date, order: a, max: 40, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

schedule_new:
  url:             /nueva/programacion
  param:           { module: Schedule, action: edit }

schedule_edit:
  url:             /editar/programacion/:slug
  param:           { module: Schedule, action: edit }
  requirements:    { slug: '[\w-]+' }

schedule_delete:
  url:             /eliminar/programacion/:slug
  param:           { module: Schedule, action: delete }
  requirements:    { slug: '[\w-,]+' }


########################
####### Place ##########
########################

#Place
place_show:
  url:             /mostrar/lugar/:slug
  param:           { module: Place, action: show }
  requirements:    { slug: \w+ }

place_list:
  url:             /lista/lugares/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Place, action: list, filter_by: id, filter: 0, order_by: name, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

place_new:
  url:             /nuevo/lugar
  param:           { module: Place, action: edit }

place_edit:
  url:             /editar/lugar/:slug
  param:           { module: Place, action: edit }
  requirements:    { slug: '[\w-]+' }

place_delete:
  url:             /eliminar/lugar/:slug
  param:           { module: Place, action: delete }
  requirements:    { slug: '[\w-,]+' }
  
##########################
####### Company ##########
##########################

#Company
company_show:
  url:             /mostrar/empresa/:slug
  param:           { module: Company, action: show }
  requirements:    { slug: \w+ }

company_list:
  url:             /lista/empresas/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Company, action: list, filter_by: id, filter: 0, order_by: name, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

company_new:
  url:             /nueva/empresa
  param:           { module: Company, action: edit }

company_edit:
  url:             /editar/empresa/:slug
  param:           { module: Company, action: edit }
  requirements:    { slug: '[\w-]+' }

company_delete:
  url:             /eliminar/empresa/:slug
  param:           { module: Company, action: delete }
  requirements:    { slug: '[\w-,]+' }
  

###########################
########## Bus ############
###########################

#Bus
bus_show:
  url:             /mostrar/bus/:slug
  param:           { module: Bus, action: show }
  requirements:    { slug: \w+ }

bus_list:
  url:             /lista/buses/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Bus, action: list, filter_by: id, filter: 0, order_by: code, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

bus_new:
  url:             /nuevo/bus
  param:           { module: Bus, action: edit }

bus_edit:
  url:             /editar/bus/:slug
  param:           { module: Bus, action: edit }
  requirements:    { slug: '[\w-]+' }

bus_delete:
  url:             /eliminar/bus/:slug
  param:           { module: Bus, action: delete }
  requirements:    { slug: '[\w-,]+' }
  
  
  
############################
########## Crew ############
############################

#Crew
crew_show:
  url:             /mostrar/tripulacion/:slug
  param:           { module: Crew, action: show }
  requirements:    { slug: \w+ }

crew_list:
  url:             /lista/tripulacion/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: Crew, action: list, filter_by: id, filter: 0, order_by: id, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

crew_new:
  url:             /nuevo/tripulacion
  param:           { module: Crew, action: edit }

crew_edit:
  url:             /editar/tripulacion/:slug
  param:           { module: Crew, action: edit }
  requirements:    { slug: '[\w-]+' }

crew_delete:
  url:             /eliminar/tripulacion/:slug
  param:           { module: Crew, action: delete }
  requirements:    { slug: '[\w-,]+' }
  
############################
########## User ############
############################

#User
user_show:
  url:             /mostrar/usuario/:slug
  param:           { module: User, action: show }
  requirements:    { slug: \w+ }

user_list:
  url:             /lista/usuarios/:filter_by/:filter/:order_by/:order/:max/:page
  param:           { module: User, action: list, filter_by: id, filter: 0, order_by: id, order: d, max: 20, page: 1, rflow: on }
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+ }

user_new:
  url:             /nuevo/usuario
  param:           { module: User, action: edit }

user_edit:
  url:             /editar/usuario/:slug
  param:           { module: User, action: edit }
  requirements:    { slug: '[\w-]+' }

user_delete:
  url:             /eliminar/usuario/:slug
  param:           { module: User, action: delete }
  requirements:    { slug: '[\w-,]+' }
  
###########################
######### Log #############
###########################

#Log
log_login:
  url:             /
  param:           { module: Log, action: login }
  
log_logout:
  url:             /logout
  param:           { module: Log, action: logout }





###########################
######### General #########
###########################

#default
default_disabled:
  url:             /default/disabled
  param:           { module: default, action: disabled }

default_error404:
  url:             /default/error404
  param:           { module: default, action: error404 }

default_login:
  url:             /default/login
  param:           { module: default, action: login }

default_secure:
  url:             /default/secure
  param:           { module: default, action: secure }



#Error
error_delete_error:
  url:             /error/delete_error
  param:           { module: Error, action: deleteError }



#Generic
generic_get_attribute_value:
  url:             /generic/get_attribute_value
  param:           { module: Generic, action: getAttributeValue }

generic_add_dynamic_form:
  url:             /generic/add_dynamic_form
  param:           { module: Generic, action: addDynamicForm }

generic_remove_dynamic_form:
  url:             /generic/remove_dynamic_form
  param:           { module: Generic, action: removeDynamicForm }



#Home
home:
  url:             /inicio
  param:           { module: Home, action: show }
  
##############################
######### Default ############
##############################

