<?php

/**
 * BusColorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusColorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusColorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BusColor');
    }
}