<?php

/**
 * BusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bus');
    }
}