<?php

/**
 * BusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bus');
    }
    
  const
    FUEL_DISEL       = 1,
    FUEL_GNV       = 2,
    FUEL_GLP       = 3,
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0,
    USE_PERSONAL_TRANSPORT = 1;

    
  protected static
    $status        = array
                   (
                     self::STATUS_ACTIVE     => 'Si',
                     self::STATUS_INACTIVE   => 'No',
                   );
  protected static
    $fuel        = array
                   (
                     self::FUEL_DISEL     => 'Diesel',
                     self::FUEL_GNV   => 'GNV',
                     self::FUEL_GLP   => 'GLP',
                   );
  
  protected static
    $use        = array
                   (
                     self::USE_PERSONAL_TRANSPORT     => 'Transporte Personal'
                   );
  
  public function getStatuss()
  {
    return self::$status;
  } 
  
  public function getFuel()
  {
    return self::$fuel;
  }
  
  public function getUse()
  {
    return self::$use;
  }  
}