<?php

/**
 * CrewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrewTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Crew');
    }
  const
    PILOT_A  = 1,
    PILOT_B  = 2,
    AUXILIAR = 3,
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $positions     = array
                   (
                     self::PILOT_A  => 'piloto A',
                     self::PILOT_B  => 'Piloto B',
                     self::AUXILIAR => 'Tripulante Auxiliar'
                   );
    
  protected static
    $status        = array
                   (
                     self::STATUS_ACTIVE     => 'Si'  ,
                     self::STATUS_INACTIVE   => 'No',
                   );
                             
  public function getStatuss()
  {
    return self::$status;
  }  
  
  public function getPositions()
  {
    return self::$positions;
  }
  
  public function updateQueryForList(DoctrineQuery $q)
  {
    $q->innerJoin('c.Bus b');
  }
}