<?php

/**
 * DisembarkingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisembarkingTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisembarkingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Disembarking');
    }
}