<?php

/**
 * RoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Role');
    }
    
const
    ADMIN     = 'AD',
    CLIENT    = 'CL';    
}