<?php

/**
 * Schedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    polosac
 * @subpackage model
 * @author     David Joan Tataje Mendoza <davidtataje@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Schedule extends BaseSchedule
{
  public function getActiveStr()
  {  	
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }
  
  public function getFormattedTravelDate($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getTravelDate(), $format);
  }  
}
