<?php

/**
 * ScheduleDetailPassengerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleDetailPassengerTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleDetailPassengerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScheduleDetailPassenger');
    }
}