<?php

/**
 * ScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Schedule');
    }
    const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  } 
  

    
  public function updateQueryForList(DoctrineQuery $q)
  {
    $q->innerJoin('s.Bus b');
    $q->innerJoin('s.PlaceFrom pf');
    $q->innerJoin('s.PlaceTo pt');
  }
}