<?php

/**
 * ScheduleDetailPassengerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleDetailPassengerTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleDetailPassengerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScheduleDetailPassenger');
    }
    
    public function getNewRank()
  {
  	 $q = $this->createQuery('a')
  	           ->addSelect('MAX(rank)');
  	           
  	 $dato = $q->execute()->getFirst()->toArray();
  	 return $dato['MAX']+1;
  	 
  } 
    
      public function getQuery($slug = null)
  {
    $slug = (is_null($slug))?sfContext::getInstance()->getUser()->getCompanySlug():$slug;
    
    $q = $this->createAliasQuery()
         ->innerJoin('sdp.Passenger p')   
         ->innerJoin('p.Company c')
         ->innerJoin('p.Boarding b');
 
      $q->addWhere('c.slug = ?',$slug);    
    
    $q->addWhere('p.active = ?', 1);
    return $q;
  }  
  
            
            
    
    public function getList($schedule_slug, $bus_size = 40)
    {
        
      $schedule = Doctrine::getTable('Schedule')->findOneBySlug($schedule_slug);
      $data = null;
      $q = $this->createAliasQuery();
      $q->innerJoin('sdp.Passenger p')
        ->innerJoin('sdp.ScheduleDetail sd')
        ->innerJoin('sd.Schedule s')
        ->where('s.slug = ?', $schedule_slug);
         
      $count = 0;
      $id = 0;

      
      if($schedule->getPlaceFrom()->getName() == 'Lima')
      {
      foreach($q->execute() as $key => $passenger)
      {
          if($key == 2)
          {
              $data[2] = array('3','RESERVADO AUXILIAR', '-', '-','-','-');
              $count++;
              $id++;
          }
        $count++;
        $data[$id] = array($count, sprintf('%s %s',$passenger->getPassenger()->getLastName(),
                $passenger->getPassenger()->getFirstName()),
                $passenger->getPassenger()->getDni(), 
                $passenger->getPassenger()->getCompanyName(), 
                $passenger->getPassenger()->getBoardingName(),
                $passenger->getPassenger()->getDisembarkingName()
                
                );
        
        $id++;
      }          
      }
      else
      {
      foreach($q->execute() as $key => $passenger)
      {
          if($key == 2)
          {
              $data[2] = array('3','RESERVADO AUXILIAR', '-', '-','-','-');
              $count++;
              $id++;
          }
        $count++;
        $data[$id] = array($count, sprintf('%s %s',$passenger->getPassenger()->getLastName(),
                $passenger->getPassenger()->getFirstName()),
                $passenger->getPassenger()->getDni(), 
                $passenger->getPassenger()->getCompanyName(), 
                $passenger->getPassenger()->getDisembarkingName(),
                $passenger->getPassenger()->getBoardingName() 
                );
        
        $id++;
      }     
      }

      
      $cant_actual = count($data);
      
      $falta = $bus_size - $cant_actual;
      
      $counter=0;
      for ($i = 0; $i<$falta; $i++)
      {$counter++;
        $data[$cant_actual+$counter] = array($cant_actual+$counter,'RESERVADO', '-', '-','-', '-');    
      }
      
      return $data;
    }      
}