<?php

/**
 * ScheduleDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleDetailTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScheduleDetail');
    }
}