<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
  public function findOneByLowerCaseEmail($email)
  {
    $q = $this->createAliasQuery()
         ->where('u.email = ?', strtolower($email));
         
    return $q->fetchOne();
  }
  
  public function findOneByLowerCaseUsername($username)
  {
    $q = $this->createAliasQuery()
         ->where('u.username = ?', strtolower($username));
         
    return $q->fetchOne();
  } 
  
  public function updateQueryForList(DoctrineQuery $q)
  {
    $q->innerJoin('u.Company c');
    $q->innerJoin('u.Role r');
  } 
  
  public function getEmailBosses($company_slug)
  {
      $response = array();
    $q = $this->createAliasQuery();
    $q->innerJoin('u.Company c');
         $q->where('c.slug = ?', $company_slug);
         
         foreach($q->execute() as $user)
         {
           $response[$user->getEmailBoss()]  = 'Jefe(a) de '.$user->getRealName();
           $response[$user->getEmail()]  = $user->getRealName();
         }
         
         
    return $response;
  }   
}