<?php

/**
 * VisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisitTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Visit');
    }
}