
Schedule:
  tableName:                 t_schedule
  actAs:
    SluggableExt:            { fields: [ travel_date ] }
    Timestampable:
  columns:
    id:                      { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    bus_id:                  { type: integer  , length: 20                    , notnull: true               }
    place_from_id:           { type: integer  , length: 20                    , notnull: true               }
    place_to_id:             { type: integer  , length: 20                    , notnull: true               }
    travel_date:             { type: date }
    travel_time:             { type: time }
    number:                  { type: string   , length: 2                     , notnull: true               }
    active:                  { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
  relations:
    Bus:                     { class: Bus , local: bus_id , foreign: id , type: one  , alias: Bus , onDelete: RESTRICT, onUpdate: CASCADE }
    PlaceFrom:               { class: Place , local: place_from_id , foreign: id , type: one ,alias: PlaceFrom , onDelete: RESTRICT, onUpdate: CASCADE }
    PlaceTo:                 { class: Place , local: place_to_id   , foreign: id , type: one ,alias: PlaceTo , onDelete: RESTRICT, onUpdate: CASCADE }
    ScheduleDetail:          { class: ScheduleDetail , local: id,   foreign: schedule_id   , type: many , alias: ScheduleDetails }
  options:
    symfony:                 { filter: false, form: true }
    boolean_columns:         [ active ]
    
ScheduleDetail:
  tableName:                 t_schedule_detail
  actAs:
    Timestampable:
  columns:
    id:                      { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    schedule_id:             { type: integer  , length: 20                    , notnull: true               }
    company_id:              { type: integer  , length: 20                    , notnull: true               }
    qty_seats:               { type: string   , length: 100                   , notnull: true               }
    active:                  { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
  relations:
    Schedule:                { class: Schedule  , local: schedule_id , foreign: id , type: one , alias: Schedule , onDelete: CASCADE, onUpdate: CASCADE }
    Company:                 { class: Company   , local: company_id  , foreign: id , type: one , alias: Company  , onDelete: CASCADE, onUpdate: CASCADE }
    Passenger:               { class: Passegner , local: schedule_detail_id , foreign: passenger_id , alias: Passengers, refClass: ScheduleDetailPassenger }
  options:
    symfony:                 { filter: false, form: true }
    boolean_columns:         [ active ]
    
    
Boarding:
  tableName:                           t_boarding
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    name:                              { type: string   , length: 100                   , notnull: true               }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_name:                            { fields: [ name ]                               , type: unique                }
  #relations:
  #  Passenger:                         { class: Passenger , local: id,   foreign: boarding_id   , type: many , alias: Passengers }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]  

  
Disembarking:
  tableName:                           t_disembarking
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    name:                              { type: string   , length: 100                   , notnull: true               }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_name:                            { fields: [ name ]                               , type: unique                }
  #relations:
  #  Passenger:                         { class: Passenger , local: id,   foreign: boarding_id   , type: many , alias: Passengers }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]  
    
    
Passenger:
  tableName:                           t_passenger
  actAs:
    SluggableExt:                      { fields: [ last_name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    boarding_id:                       { type: integer  , length: 20                    , notnull: false              }
    disembarking_id:                   { type: integer  , length: 20                    , notnull: false              }
    company_id:                        { type: integer  , length: 20                    , notnull: true               }
    dni:                               { type: string   , length: 8                     , notnull: true               }
    first_name:                        { type: string   , length: 100                   , notnull: true               }    
    last_name:                         { type: string   , length: 100                   , notnull: true               }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_dni:                             { fields: [ dni ]                                 , type: unique                }
  relations:
    Boarding:                          { class: Boarding , local: boarding_id , foreign: id , type: one , alias: Boarding , onDelete: 'SET NULL', onUpdate: CASCADE }
    Disembarking:                      { class: Disembarking , local: disembarking_id , foreign: id , type: one , alias: Disembarking , onDelete: 'SET NULL', onUpdate: CASCADE }
    Company:                           { class: Company  , local: company_id  , foreign: id , type: one , alias: Company  , onDelete: CASCADE, onUpdate: CASCADE }
    ScheduleDetail:                    { class: ScheduleDetail , local: passenger_id , foreign: schedule_detail_id , alias: ScheduleDetails, refClass: ScheduleDetailPassenger }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]    

ScheduleDetailPassenger:
  tableName:                           t_schedule_detail_passenger
  actAs:
    Timestampable:                    { updated: { disabled: true } }
  columns:
    schedule_detail_id:               { type: integer  , length: 20 , primary: true                                                               }
    passenger_id:                     { type: integer  , length: 20 , primary: true                                                               }
    rank:                             { type: integer  , length: 20         }
  relations:
    ScheduleDetail:                   { class: ScheduleDetail , local: schedule_detail_id , foreign: id, type: one , alias: ScheduleDetail , onDelete: CASCADE , onUpdate: CASCADE }
    Passenger:                        { class: Passenger      , local: passenger_id       , foreign: id, type: one , alias: Passenger      , onDelete: CASCADE , onUpdate: CASCADE }
  options:
    symfony:                          { filter: false, form: false }    