#tripulacion
Crew:
  tableName:                           t_crew
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                    }
    bus_id:                            { type: integer  , length: 20 ,                                                                           }
    name:                              { type: string   , length: 100                   , notnull: true                                          }    
    dni:                               { type: string   , length: 8                     , notnull: true                                          }
    driver_license:                    { type: string   , length: 20                    , notnull: false                                         }
    position:                          { type: string   , length: 1  , fixed: true      , notnull: true , default: 1                             }    
    phone:                             { type: string   , length: 100                   , notnull: false                                         }
    natclar:                           { type: date }
    mtc:                               { type: date }
    expired_drivers_license:           { type: date }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1                             }
  indexes:
    u_name:                            { fields: [ name ]                               , type: unique                                           }
    u_dni:                             { fields: [ dni ]                               , type: unique                                            }
  relations:
    #Post:                              { class: Post        , local: category_id   , foreign: post_id     , alias: Posts, refClass: PostCategory }
    #Menu:                              { class: Menu        , local: id            , foreign: category_id , type: many, alias: Menus             }
    Bus:                              { class: Bus , local: bus_id , foreign: id , type: one , alias: Bus , onDelete: RESTRICT, onUpdate: CASCADE }    
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]        
    