Schedule:
  tableName:                 t_schedule
  actAs:
    SluggableExt:            { fields: [ travel_date ] }
    Timestampable:
  columns:
    id:                      { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    bus_id:                  { type: integer  , length: 20                    , notnull: true               }
    place_from_id:           { type: integer  , length: 20                    , notnull: true               }
    place_to_id:             { type: integer  , length: 20                    , notnull: true               }
    travel_date:             { type: date }
    travel_time:             { type: time }
    active:                  { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
  relations:
    Bus:                     { class: Bus , local: bus_id , foreign: id , type: one  , alias: Bus , onDelete: RESTRICT, onUpdate: CASCADE }
    PlaceFrom:               { class: Place , local: place_from_id , foreign: id , type: one ,alias: PlaceFrom , onDelete: RESTRICT, onUpdate: CASCADE }
    PlaceTo:                 { class: Place , local: place_to_id   , foreign: id , type: one ,alias: PlaceTo , onDelete: RESTRICT, onUpdate: CASCADE }
    ScheduleDetail:          { class: ScheduleDetail , local: id,   foreign: schedule_id   , type: many , alias: ScheduleDetails }
  options:
    symfony:                 { filter: false, form: true }
    boolean_columns:         [ active ]
    
ScheduleDetail:
  tableName:                 t_schedule_detail
  actAs:
    Timestampable:
  columns:
    id:                      { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    schedule_id:             { type: integer  , length: 20                    , notnull: true               }
    company_id:              { type: integer  , length: 20                    , notnull: true               }
    qty_seats:               { type: string   , length: 100                   , notnull: true               }
    active:                  { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
  relations:
    Schedule:                { class: Schedule , local: schedule_id , foreign: id , type: one , alias: Schedule , onDelete: RESTRICT, onUpdate: CASCADE }
    Company:                 { class: Company  , local: company_id  , foreign: id , type: one , alias: Company  , onDelete: RESTRICT, onUpdate: CASCADE }
  options:
    symfony:                 { filter: false, form: true }
    boolean_columns:         [ active ]
    
    
Boarding:
  tableName:                           t_boarding
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    name:                              { type: string   , length: 100                   , notnull: true               }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_name:                            { fields: [ name ]                               , type: unique                }
  relations:
    Passenger:                         { class: Passenger , local: id,   foreign: boarding_id   , type: many , alias: Passengers }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]  
  
Passenger:
  tableName:                           t_passenger
  actAs:
    SluggableExt:                      { fields: [ names ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    boarding_id:                       { type: integer  , length: 20                    , notnull: false              }
    company_id:                        { type: integer  , length: 20                    , notnull: false              }
    dni:                               { type: string   , length: 8                     , notnull: true               }
    names:                             { type: string   , length: 100                   , notnull: true               }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_name:                            { fields: [ names ]                               , type: unique                }
  relations:
    Boarding:                          { class: Boarding , local: boarding_id , foreign: id , type: one , alias: Boarding , onDelete: RESTRICT, onUpdate: CASCADE }
    Company:                           { class: Company  , local: company_id  , foreign: id , type: one , alias: Company  , onDelete: RESTRICT, onUpdate: CASCADE }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]    
    
    
ScheduleDetailPassenger:
  tableName:                 t_schedule_detail_passenger
  actAs:
    Timestampable:
  columns:
    id:                      { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    schedule_detail_id:      { type: integer  , length: 20                    , notnull: true               }
    passenger_id:            { type: integer  , length: 20                    , notnull: true               }
    seat:                    { type: string   , length: 100                   , notnull: true               }
    active:                  { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
  relations:
    ScheduleDetail:          { class: ScheduleDetail , local: schedule_detail_id , foreign: id , type: one , alias: ScheduleDetail , onDelete: RESTRICT, onUpdate: CASCADE }
    Passenger:               { class: Passenger      , local: passenger_id       , foreign: id , type: one , alias: Passenger      , onDelete: RESTRICT, onUpdate: CASCADE }
  options:
    symfony:                 { filter: false, form: true }
    boolean_columns:         [ active ]