#Contact
Contact:
  tableName:                           t_contact
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                    }
    company_id:                        { type: integer  , length: 20                    , notnull: true                                          }
    name:                              { type: string   , length: 100                   , notnull: true                                          }#placa
    email:                             { type: string   , length: 100                   , notnull: true                                          }#placa
    phone:                             { type: string   , length: 100                   , notnull: false                                         }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1                             }
  indexes:
  relations:
    Company:                           { class: Company , local: company_id , foreign: id , type: one , alias: Company , onDelete: RESTRICT, onUpdate: CASCADE }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]
    